language: generic
jobs:
  include:
    - stage: test
      name: "mock build test"
      script:
        - docker run -dit --name mock -v "$(pwd)":/mockdir --cap-add=SYS_ADMIN --privileged imlteam/mock
        - docker exec -it mock bash -xec 'chown root.root /mockdir/*'
        - docker exec -it mock bash -xec 'cd /mockdir && make -f .copr/Makefile outdir=/mockdir'
        - docker exec -it mock bash -xec 'mock /tmp/_topdir/SRPMS/python-massiviu-*.el*.src.rpm -v --enable-network'
    - stage: cd
      name: "Continuous Deployment"
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-devel
        - export PACKAGE=python-massiviu
        - export SPEC=python-massiviu.spec
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
    - stage: deploy-copr-r5.0
      name: "Copr 5.0 deploy"
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-5.0
        - export PACKAGE=python-massiviu
        - export SPEC=python-massiviu.spec
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e PROD="True" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
stages:
  - test
  - name: cd
    if: branch = master AND type = push AND fork = false
  - name: deploy-copr-r5.0
    if: branch =~ ^v\d+\.\d+\.\d+-.+-r5\.0$
